FLAG=-g
LIB=-lpthread
CPP=g++
CC=gcc

p4: p4.cpp
	${CPP} ${FLAG} -o p4 p4.cpp ${LIB}

p3: p3.cpp
	${CPP} ${FLAG} -o p3 p3.cpp ${LIB}

p2: p2.cpp
	${CPP} ${FLAG} -o p2 p2.cpp ${LIB}

p1: p1.cpp
	${CPP} ${FLAG} -o p1 p1.cpp ${LIB}

clean:
	rm -rf p1 p2 p3	p4
