[package]
name = "mcast"
version = "0.1.0"
authors = ["Sergey Matyukevich <geomatsi@gmail.com>"]
edition = "2018"

[dependencies]
pretty-hex = "0.1.1"
nix = "0.20.2"

[dependencies.structopt]
version = "0.3"
default-features = false
